// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "contents",
    columns: [
      { name: "tmdb_id", type: "int" },
      { name: "title", type: "text" },
      { name: "tagline", type: "text" },
      { name: "overview", type: "text" },
      { name: "release_date", type: "datetime" },
      { name: "poster_url", type: "text" },
      { name: "backdrop_url", type: "text" },
      { name: "type", type: "text" },
    ],
    revLinks: [{ column: "content", table: "content_genres" }],
  },
  {
    name: "genres",
    columns: [
      { name: "genre_id", type: "int" },
      { name: "name", type: "text" },
    ],
    revLinks: [{ column: "genre", table: "content_genres" }],
  },
  {
    name: "content_genres",
    columns: [
      { name: "content", type: "link", link: { table: "contents" } },
      { name: "genre", type: "link", link: { table: "genres" } },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Contents = InferredTypes["contents"];
export type ContentsRecord = Contents & XataRecord;

export type Genres = InferredTypes["genres"];
export type GenresRecord = Genres & XataRecord;

export type ContentGenres = InferredTypes["content_genres"];
export type ContentGenresRecord = ContentGenres & XataRecord;

export type DatabaseSchema = {
  contents: ContentsRecord;
  genres: GenresRecord;
  content_genres: ContentGenresRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://lostsandye-s-workspace-v76kqh.us-east-1.xata.sh/db/safe",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
